### ISSUE TITLE
Three level model

### ISSUE THREAD

**Issue by mccalluc** [WGBH/stock-sales-admin#2]
I want to confirm that this is the right data model for the Stock Sales admin: 
- *File* has technical metadata, and higher level program information.
- *Scene* is where the fine grained descriptive information goes.
- *Clip* is separate because it looks like the same scenic information applies to successive clips.

This doesn't need to influence anything in the public website, which can still be based on flat records exported from this structure.

Does this make sense? I'm not getting into how new records would be created: I want to be sure that this makes sense.

File record:
```
                       # Editable data:
                 type: Beta SP
              barcode: Barcode40434
          tape_number: 
           drive_name: 
          folder_name: 
            file_name: 
               series: FRONTLINE
              program: 
              episode: 
               format: 
         aspect_ratio: 4:3
    frames_per_second: 
           scan_lines: 
                codec: 
      digital_wrapper: 

                       # Links to scenes:
               Scenes: Counting prayer beads
                       At the market
                       End of Ramadan
```

Scene record:
```
Counting prayer beads
                       # Editable data:
           event_date: 1998-12-01  
       event_location: Khartoum, Sudan, Africa
           clip_title: Counting prayer beads
     clip_description: CU hand holding string of wooden prayer beads
        clip_keywords: mosques, Muslims, prayers, praying
             category: Culture/Society

                       # Links to clips:
                Clips: 00:03:49;00
                       00:04:05;00
                       00:04:15;00
```

Clip record:
```
              time_in: 00:03:49;00
             time_out: 00:04:05;00
               length: 00:00:15;28
```
